# Database
db=postgres
db-url=jdbc:postgresql://lkfl-postgres:5432/keycloak
db-username=lkfl
db-password=lkfl-server-password

# Hostname - HTTPS via external Nginx reverse proxy
hostname=dev.april.ukituki.tech
hostname-strict=false
hostname-strict-https=false
proxy-headers=xforwarded
http-enabled=true
