// Brand sync — генерация CSS файлов для Keycloak из tenant_brand_config.
//
// Подключается к PostgreSQL, читает все tenant_brand_config записи,
// генерирует brand-{slug}.css файлы в output directory.
// On-demand: запускается вручную или в CI при изменении бренд-конфига.
//
// Запуск:
//
//	DB_DSN="postgresql://..." OUTPUT_DIR="./infra/keycloak/theme/lkfl/login/resources/css" go run ./cmd/brand-sync/
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
)

// BrandRecord — одна запись из tenant_brand_config.
type BrandRecord struct {
	TenantID       uuid.UUID
	TenantSlug     string
	PrimaryColor   string
	SecondaryColor string
	BrandName      *string
	CSSVariables   map[string]string
}

// cssData — данные для шаблонизации CSS.
type cssData struct {
	BrandName string
	Slug      string
	Tokens    []cssToken
}

// cssToken — ключ-значение токена для детерминированного вывода.
type cssToken struct {
	Key   string
	Value string
}

var brandCSSTemplate = template.Must(template.New("brand").Parse(`// Generated by brand-sync — DO NOT EDIT manually
// Brand: {{.BrandName}} ({{.Slug}})
:root {
{{- range .Tokens }}
  --brand-{{ .Key }}: {{ .Value }};
{{- end }}
}
`))

func main() {
	dsn := os.Getenv("DB_DSN")
	if dsn == "" {
		fmt.Println("DB_DSN required")
		os.Exit(1)
	}

	outputDir := os.Getenv("OUTPUT_DIR")
	if outputDir == "" {
		outputDir = "infra/keycloak/theme/lkfl/login/resources/css"
	}

	conn, err := pgx.Connect(context.Background(), dsn)
	if err != nil {
		fmt.Fprintf(os.Stderr, "connect error: %v\n", err)
		os.Exit(1)
	}
	defer func() { _ = conn.Close(context.Background()) }()

	ctx := context.Background()

	// Read all tenant brand configs
	rows, err := conn.Query(ctx, `
		SELECT
			b.tenant_id,
			t.slug,
			b.primary_color,
			b.secondary_color,
			b.brand_name,
			b.css_variables
		FROM lkfl_platform.tenant_brand_config b
		JOIN lkfl_platform.tenants t ON t.id = b.tenant_id
		WHERE t.status = 'active'
		ORDER BY t.slug
	`)
	if err != nil {
		fmt.Fprintf(os.Stderr, "query error: %v\n", err)
		os.Exit(1)
	}
	defer rows.Close()

	var records []BrandRecord
	for rows.Next() {
		var r BrandRecord
		var cssVars json.RawMessage
		err := rows.Scan(&r.TenantID, &r.TenantSlug, &r.PrimaryColor, &r.SecondaryColor, &r.BrandName, &cssVars)
		if err != nil {
			fmt.Fprintf(os.Stderr, "scan error: %v\n", err)
			os.Exit(1)
		}

		// Parse css_variables JSONB
		if len(cssVars) > 0 {
			r.CSSVariables = make(map[string]string)
			if err := json.Unmarshal(cssVars, &r.CSSVariables); err != nil {
				fmt.Fprintf(os.Stderr, "unmarshal css_variables for %s: %v\n", r.TenantSlug, err)
			}
		}

		records = append(records, r)
	}

	if err = rows.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "rows error: %v\n", err)
		os.Exit(1)
	}

	if len(records) == 0 {
		fmt.Println("No active tenant brand configs found")
		return
	}

	// Ensure output directory exists
	if err := os.MkdirAll(outputDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir error: %v\n", err)
		os.Exit(1)
	}

	created := 0
	for _, r := range records {
		outputPath := filepath.Join(outputDir, "brand-"+r.TenantSlug+".css")

		css, err := generateCSS(r)
		if err != nil {
			fmt.Fprintf(os.Stderr, "generate CSS error for %s: %v\n", r.TenantSlug, err)
			continue
		}

		if err := os.WriteFile(outputPath, []byte(css), 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "write error for %s: %v\n", r.TenantSlug, err)
			continue
		}

		brandName := "unknown"
		if r.BrandName != nil {
			brandName = *r.BrandName
		}
		fmt.Printf("  Created: %s (%s)\n", outputPath, brandName)
		created++
	}

	fmt.Printf("\nGenerated %d CSS files in %s\n", created, outputDir)
}

func generateCSS(r BrandRecord) (string, error) {
	brandName := "Brand"
	if r.BrandName != nil {
		brandName = *r.BrandName
	}

	// Sort tokens by key for deterministic output
	tokens := sortedTokens(r.CSSVariables)

	var buf strings.Builder
	err := brandCSSTemplate.Execute(&buf, cssData{
		BrandName: brandName,
		Slug:      r.TenantSlug,
		Tokens:    tokens,
	})

	return buf.String(), err
}

// sortedTokens преобразует map[string]string в отсортированный слайс cssToken
// для детерминированного вывода CSS (map обход в Go не детерминирован).
func sortedTokens(m map[string]string) []cssToken {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	tokens := make([]cssToken, 0, len(keys))
	for _, k := range keys {
		tokens = append(tokens, cssToken{Key: k, Value: m[k]})
	}
	return tokens
}
